### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by jmkuhn** [JeffreySarnoff/CompoundPeriods.jl#7]
Please tag a new version that will work with Julia 1.11.  The [previous](https://github.com/JuliaRegistries/General/pull/102904) auto-merge failed because version 0.5.2 was skipped.

**Comment by JeffreySarnoff** [comment]
Please give me more information, if you have it.
What needs to be done with a new version so it works with Julia 1.11?

**Comment by jmkuhn** [comment]
You just need a release with https://github.com/JeffreySarnoff/CompoundPeriods.jl/pull/6 merged.  The current #master works with 1.11, but version 0.5.1 doesn't work.

**Comment by JeffreySarnoff** [comment]
Did the new version resolve this?

**Comment by jmkuhn** [comment]
Yes, thank you.
